2022-03-23 00:15:11,842 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x0000022A35724280>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-23 00:15:11,900 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-23 00:16:38,026 INFO core.py Установлено соедение с ПК ('127.0.0.1', 55666)
2022-03-23 00:16:38,537 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647983798.0488825, 'user': {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0bbfBT1n5Rg9HZdMLqw7\nKI9Jvj7uqo4NbX5x+3vpiN1iptLbh7ULuKIfTGLHbG60YEFTjhF2mC4dKIS413gY\n4K89784mAzDgA8Lo0Iw5cE7rWAkf6frdIC0kSUDUJOdLRLJFMTJ6D/3oB8FiNfG5\n+XkmmMjmQfUOrRNSjVaRl/qceXnETUZDE/AJBnckXZBFzrMI4zJjDFRH2kJdsj2R\nTPx92zZE9/NR5mTlKehQHGdEJHgvxEY80uwQ61rJhyr4wzl+LMHkUdgDGEuuZewY\n1lsB2gcBgcPREJ69t0qp6/9rMVkxRKmNgr8tc5IUv8saQc7yfL4bFMYbaOlnXUnI\n5QIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-23 00:16:38,538 DEBUG core.py Start auth process for {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0bbfBT1n5Rg9HZdMLqw7\nKI9Jvj7uqo4NbX5x+3vpiN1iptLbh7ULuKIfTGLHbG60YEFTjhF2mC4dKIS413gY\n4K89784mAzDgA8Lo0Iw5cE7rWAkf6frdIC0kSUDUJOdLRLJFMTJ6D/3oB8FiNfG5\n+XkmmMjmQfUOrRNSjVaRl/qceXnETUZDE/AJBnckXZBFzrMI4zJjDFRH2kJdsj2R\nTPx92zZE9/NR5mTlKehQHGdEJHgvxEY80uwQ61rJhyr4wzl+LMHkUdgDGEuuZewY\n1lsB2gcBgcPREJ69t0qp6/9rMVkxRKmNgr8tc5IUv8saQc7yfL4bFMYbaOlnXUnI\n5QIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-23 00:16:38,539 DEBUG core.py Unknown username, sending {'response': 400, 'error': 'Пользователь не зарегистрирован.'}
2022-03-23 00:17:21,557 INFO core.py Установлено соедение с ПК ('127.0.0.1', 55761)
2022-03-23 00:17:22,062 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647983841.5866811, 'user': {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0bbfBT1n5Rg9HZdMLqw7\nKI9Jvj7uqo4NbX5x+3vpiN1iptLbh7ULuKIfTGLHbG60YEFTjhF2mC4dKIS413gY\n4K89784mAzDgA8Lo0Iw5cE7rWAkf6frdIC0kSUDUJOdLRLJFMTJ6D/3oB8FiNfG5\n+XkmmMjmQfUOrRNSjVaRl/qceXnETUZDE/AJBnckXZBFzrMI4zJjDFRH2kJdsj2R\nTPx92zZE9/NR5mTlKehQHGdEJHgvxEY80uwQ61rJhyr4wzl+LMHkUdgDGEuuZewY\n1lsB2gcBgcPREJ69t0qp6/9rMVkxRKmNgr8tc5IUv8saQc7yfL4bFMYbaOlnXUnI\n5QIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-23 00:17:22,063 DEBUG core.py Start auth process for {'account_name': 'user_100', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0bbfBT1n5Rg9HZdMLqw7\nKI9Jvj7uqo4NbX5x+3vpiN1iptLbh7ULuKIfTGLHbG60YEFTjhF2mC4dKIS413gY\n4K89784mAzDgA8Lo0Iw5cE7rWAkf6frdIC0kSUDUJOdLRLJFMTJ6D/3oB8FiNfG5\n+XkmmMjmQfUOrRNSjVaRl/qceXnETUZDE/AJBnckXZBFzrMI4zJjDFRH2kJdsj2R\nTPx92zZE9/NR5mTlKehQHGdEJHgvxEY80uwQ61rJhyr4wzl+LMHkUdgDGEuuZewY\n1lsB2gcBgcPREJ69t0qp6/9rMVkxRKmNgr8tc5IUv8saQc7yfL4bFMYbaOlnXUnI\n5QIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-23 00:17:22,064 DEBUG core.py Correct username, starting passwd check.
2022-03-23 00:17:22,065 DEBUG core.py Auth message = {'response': 511, 'bin': 'decd1985895c90fe9dfa4e7c25eab71d8e39baea7c957e6e0defca1acd5ea53ff280f15fff6089c2c992656abf604c439b7074bf26c0a17432bfec8ea8a89926'}
2022-03-23 00:17:22,590 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647983842.0684135, 'account_name': 'user_100'}
2022-03-23 00:17:23,103 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647983842.6211414, 'user': 'user_100'}
2022-03-23 00:17:59,826 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647983879.171141, 'account_name': 'user_100'}
2022-03-23 00:17:59,827 INFO core.py Клиент ('127.0.0.1', 55761) отключился от сервера.
2022-03-23 00:18:25,667 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x0000022A35724280>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
2022-03-23 01:11:08,935 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x00000250420C4280>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-23 01:11:08,996 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-23 01:11:36,068 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x00000250420C4280>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
2022-03-23 02:38:42,635 DEBUG server.py Была вызвана функция _make_config c параметрами (<__main__.Server object at 0x0000019D55D28670>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции __init__
2022-03-23 02:38:42,678 INFO core.py Запущен сервер, порт для подключений: 7778 , адрес с которого принимаются подключения: . Если адрес не указан, принимаются соединения с любых адресов.
2022-03-23 02:39:43,160 INFO core.py Установлено соедение с ПК ('127.0.0.1', 58930)
2022-03-23 02:39:43,665 DEBUG core.py Разбор сообщения от клиента : {'action': 'presence', 'time': 1647992383.1893823, 'user': {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo15rcpXReGa4fVUTIdUX\nxtvC1Oz207K4MpqVa7Ye5IQZSEoDvVOILLyvHM+0haNqw1xmMdrYjCRuhUzNhwOy\nwOSKzueeX+yszukIu13dwA+RO1hs69ZFeCca+lyXap+AiD1Ef4DwsVZL9SIR9RVg\nAlgJAeZFSozvnOoQKILMG9K8ig/xYbbgfX1/cootsSv3ueSN4tr+jtofSmdYipPO\n8Z5fBZtACJfO/d9XU9xjoclTiqWG4sei9a1rHs7AOGDJ7W3xpVPvgzMcSqOUAFPS\n8xU8qR0TUBDfXCyWX5wGykSWtvV9lbvPfLBOckGpX5jVQhRygpPoYTk2gEKEBI8C\ngwIDAQAB\n-----END PUBLIC KEY-----'}}
2022-03-23 02:39:43,666 DEBUG core.py Start auth process for {'account_name': 'user_1', 'pubkey': '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo15rcpXReGa4fVUTIdUX\nxtvC1Oz207K4MpqVa7Ye5IQZSEoDvVOILLyvHM+0haNqw1xmMdrYjCRuhUzNhwOy\nwOSKzueeX+yszukIu13dwA+RO1hs69ZFeCca+lyXap+AiD1Ef4DwsVZL9SIR9RVg\nAlgJAeZFSozvnOoQKILMG9K8ig/xYbbgfX1/cootsSv3ueSN4tr+jtofSmdYipPO\n8Z5fBZtACJfO/d9XU9xjoclTiqWG4sei9a1rHs7AOGDJ7W3xpVPvgzMcSqOUAFPS\n8xU8qR0TUBDfXCyWX5wGykSWtvV9lbvPfLBOckGpX5jVQhRygpPoYTk2gEKEBI8C\ngwIDAQAB\n-----END PUBLIC KEY-----'}
2022-03-23 02:39:43,671 DEBUG core.py Correct username, starting passwd check.
2022-03-23 02:39:43,674 DEBUG core.py Auth message = {'response': 511, 'bin': '5813aa09a26d41810928ca435b9702cb26e7d9e9d022e4f53f382b7322aff1e7e4cba2af937a5c92ebc737afb9eecc34a26767f05b5b493cf922c9a49b6ab54a'}
2022-03-23 02:39:44,193 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_users', 'time': 1647992383.6766937, 'account_name': 'user_1'}
2022-03-23 02:39:44,710 DEBUG core.py Разбор сообщения от клиента : {'action': 'get_contacts', 'time': 1647992384.2183173, 'user': 'user_1'}
2022-03-23 02:39:48,793 DEBUG core.py Разбор сообщения от клиента : {'action': 'exit', 'time': 1647992388.66445, 'account_name': 'user_1'}
2022-03-23 02:39:48,794 INFO core.py Клиент ('127.0.0.1', 58930) отключился от сервера.
2022-03-23 02:39:57,165 DEBUG server.py Была вызвана функция start c параметрами (<__main__.Server object at 0x0000019D55D28670>,), {}. Вызов из модуля __main__. Вызов из функции main().Вызов из функции <module>
